# Generated by Django 6.0.6 on 2026-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(choices=[('bi-globe', 'Desarrollo Web'), ('bi-gear-fill', 'Sistemas de Gestión'), ('bi-cpu', 'Automatización'), ('bi-server', 'APIs y Backend'), ('bi-plug', 'Integraciones'), ('bi-lightbulb', 'Consultoría'), ('bi-phone', 'Mobile'), ('bi-shield-check', 'Seguridad'), ('bi-graph-up', 'Analytics'), ('bi-cloud', 'Cloud')], default='bi-globe', max_length=50, verbose_name='Ícono Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destacado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Nexus Studio Code', max_length=100, verbose_name='Nombre de la empresa')),
                ('tagline', models.CharField(default='Transformamos ideas en soluciones digitales', max_length=200, verbose_name='Eslogan')),
                ('hero_title', models.CharField(default='Desarrollo de Software a Medida', max_length=200, verbose_name='Título Hero')),
                ('hero_subtitle', models.TextField(default='Creamos soluciones tecnológicas innovadoras que impulsan tu negocio al siguiente nivel.', verbose_name='Subtítulo Hero')),
                ('about_history', models.TextField(blank=True, verbose_name='Historia')),
                ('about_mission', models.TextField(blank=True, verbose_name='Misión')),
                ('about_vision', models.TextField(blank=True, verbose_name='Visión')),
                ('about_values', models.TextField(blank=True, verbose_name='Valores')),
                ('email', models.EmailField(default='info@nexusstudiocode.com', max_length=254, verbose_name='Email principal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta descripción SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Keywords SEO')),
                ('google_analytics', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=30, verbose_name='Red social')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('value', models.PositiveIntegerField(verbose_name='Valor numérico')),
                ('suffix', models.CharField(blank=True, default='+', max_length=10, verbose_name='Sufijo')),
                ('icon', models.CharField(default='bi-trophy', max_length=50, verbose_name='Ícono Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('icon_class', models.CharField(blank=True, help_text='Clase devicon o similar', max_length=100, verbose_name='Clase CSS del ícono')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG del ícono')),
                ('color', models.CharField(default='#00ff88', max_length=10, verbose_name='Color hex')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('client_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('client_company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('message', models.TextField(verbose_name='Testimonio')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Calificación (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
