# Generated by Django 5.2.17 on 2026-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('category', models.CharField(choices=[('general', 'General & Contratación'), ('process', 'Metodología & Plazos'), ('tech', 'Tecnología & Propiedad Intelectual'), ('payment', 'Presupuestos & Pagos')], default='general', max_length=20, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', max_length=5, verbose_name='Número de Paso (ej: 01)')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Subtítulo / Objetivo')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('icon', models.CharField(default='bi-compass', max_length=50, verbose_name='Ícono Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paso de Metodología',
                'verbose_name_plural': 'Metodología de Trabajo',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono / WhatsApp')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Empresa / Organización')),
                ('project_type', models.CharField(max_length=100, verbose_name='Tipo de Proyecto')),
                ('features', models.TextField(blank=True, verbose_name='Funcionalidades Requeridas')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='Rango de Presupuesto Estimado')),
                ('timeline', models.CharField(blank=True, max_length=100, verbose_name='Plazo Estimado')),
                ('description', models.TextField(blank=True, verbose_name='Detalles del Proyecto')),
                ('estimated_cost_display', models.CharField(blank=True, max_length=100, verbose_name='Cálculo Estimado Generado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_review', 'En Evaluación'), ('contacted', 'Cliente Contactado'), ('proposal_sent', 'Propuesta Enviada'), ('closed', 'Cerrada / Aceptada'), ('rejected', 'Descartada')], default='new', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Cotizaciones de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='bi-shield-check', max_length=50, verbose_name='Ícono Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Garantía / Diferencial',
                'verbose_name_plural': 'Garantías y Diferenciales',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='features_list',
            field=models.TextField(blank=True, help_text='Separar cada punto con un salto de línea', verbose_name='Características clave (1 por línea)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='experience_years',
            field=models.CharField(default='5+', max_length=10, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge_text',
            field=models.CharField(default='Disponibles para nuevos proyectos', max_length=100, verbose_name='Texto Badge Hero'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meeting_url',
            field=models.URLField(blank=True, verbose_name='URL para agendar reunión (Calendly/Meet)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_message',
            field=models.CharField(blank=True, default='Hola Nexus Studio Code, me gustaría consultar por el desarrollo de un proyecto de software.', max_length=250, verbose_name='Mensaje predeterminado de WhatsApp'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='5491155550199', help_text='Ej: 5491155550199 (sin espacios ni guiones)', max_length=30, verbose_name='Número de WhatsApp (con código país)'),
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend & APIs'), ('frontend', 'Frontend & UI/UX'), ('database', 'Bases de Datos'), ('cloud', 'Cloud, DevOps & Infraestructura'), ('ai', 'IA & Automatización')], default='backend', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('bi-globe', 'Desarrollo Web & SaaS'), ('bi-gear-fill', 'Sistemas de Gestión / ERP / CRM'), ('bi-cpu', 'Automatización & IA'), ('bi-server', 'APIs & Arquitectura Backend'), ('bi-plug', 'Integraciones & Microservicios'), ('bi-lightbulb', 'Consultoría Tecnológica & Sprint 0'), ('bi-phone', 'Aplicaciones Móviles'), ('bi-shield-check', 'Auditoría & Seguridad'), ('bi-cloud-check', 'DevOps & Cloud (AWS/Docker)'), ('bi-database-check', 'Bases de Datos & Data Engineering')], default='bi-globe', max_length=50, verbose_name='Ícono Bootstrap'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(blank=True, default='Buenos Aires, Argentina (Servicios Globales)', max_length=200, verbose_name='Dirección / Ubicación'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subtitle',
            field=models.TextField(default='Diseñamos y desarrollamos plataformas web, aplicaciones SaaS, APIs robustas y sistemas de gestión de alto rendimiento para empresas y startups.', verbose_name='Subtítulo Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='Desarrollo de Software a Medida de Alto Impacto', max_length=200, verbose_name='Título Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, default='Empresa de desarrollo de software a medida, aplicaciones web, SaaS, APIs y modernización de sistemas empresariales.', max_length=160, verbose_name='Meta descripción SEO'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_keywords',
            field=models.CharField(blank=True, default='desarrollo software a medida, software factory, python, django, react, saas, apis, argentina', max_length=300, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(blank=True, default='+54 9 11 5555-0199', max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default='Transformamos ideas en soluciones digitales escalables', max_length=200, verbose_name='Eslogan'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Clase devicon o bootstrap', max_length=100, verbose_name='Clase CSS del ícono'),
        ),
    ]
