# Generated by Django 6.0.6 on 2026-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Descripción corta')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagen principal')),
                ('technologies', models.CharField(help_text='Ej: Python, Django, PostgreSQL', max_length=300, verbose_name='Tecnologías')),
                ('public_url', models.URLField(blank=True, verbose_name='URL pública')),
                ('github_url', models.URLField(blank=True, verbose_name='Repositorio GitHub')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('maintenance', 'En Mantenimiento')], default='completed', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
