# Generated by Django 5.2.17 on 2026-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Proyecto / Caso de Estudio', 'verbose_name_plural': 'Portafolio de Proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('all', 'Todos'), ('web', 'Web App & SaaS'), ('erp', 'Sistemas de Gestión / ERP'), ('mobile', 'App Móvil'), ('api', 'APIs & Backend'), ('ai', 'Automatización & IA')], default='web', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, help_text='¿Qué problema u objetivo tenía el cliente?', verbose_name='Desafío / Problema del cliente'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Ej: FinTech, E-commerce, Logística', max_length=120, verbose_name='Cliente / Industria'),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.CharField(blank=True, default='2025', max_length=50, verbose_name='Fecha de entrega / Año'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, help_text='Ej: 40% reducción en tiempos operativos, 10k usuarios activos', verbose_name='Resultados / Métricas de impacto'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='¿Cómo lo resolvimos con arquitectura y software?', verbose_name='Solución técnica implementada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripción general'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Repositorio GitHub (opcional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado en Home'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_url',
            field=models.URLField(blank=True, verbose_name='URL pública / Demo online'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Desarrollo'), ('maintenance', 'Producción & Mantenimiento')], default='completed', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Ej: Python, Django, PostgreSQL, Docker, React', max_length=300, verbose_name='Tecnologías'),
        ),
    ]
